apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: webhook
  template:
    metadata:
      labels:
        app: webhook
    spec:
      containers:
        - image: cheapacr.azurecr.io/webhook:a674df7bf179bb2b2f6268901212cbc9e35f8686
          name: webhook
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: webhook-secret
            - configMapRef:
                name: services-config
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
      tolerations:
        - key: "kubernetes.azure.com/scalesetpriority"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
