apiVersion: x.getambassador.io/v3alpha1
kind: AmbassadorMapping
metadata:
  name: webhook
spec:
  hostname: "*"
  prefix: /api/v1/webhook/ # root
  timeout_ms: 20000
  service: kustomize-webhook:8080
